name: places
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^0.19.3
  cupertino_icons: ^1.0.2
  cupertino_range_slider: ^1.0.1
  provider: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - res/
    - res/assets/
    - res/assets/filters_icons/
    - res/assets/bottom_navigation/
  fonts:
    - family : Roboto
      fonts:
        - asset: res/Roboto-Regular.ttf

